"""Atomically migrate copied private Config classes to override-only files.

The migration never prints configuration values and replaces the source file
only after reconstructing an exactly equivalent canonical Config instance.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys
import uuid
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import fields
from datetime import time
from pathlib import Path
from typing import Any


ACCOUNTS = ("DEMO", "REAL")
PRIVATE_FILENAMES = {
    "DEMO": "demo_mt5_config.py",
    "REAL": "real_mt5_config.py",
}
CREDENTIAL_FIELDS = {
    "terminal_path": "MT5_TERMINAL_PATH",
    "login": "MT5_LOGIN",
    "password": "MT5_PASSWORD",
    "server": "MT5_SERVER",
    "monitor_write_token": "MONITOR_WRITE_TOKEN",
}


@contextmanager
def without_oppw_environment() -> Iterator[None]:
    saved = {name: value for name, value in os.environ.items() if name.startswith("OPPW_")}
    for name in saved:
        os.environ.pop(name, None)
    try:
        yield
    finally:
        for name in tuple(os.environ):
            if name.startswith("OPPW_"):
                os.environ.pop(name, None)
        os.environ.update(saved)


def load_module(path: Path):
    module_name = f"oppw_legacy_config_{uuid.uuid4().hex}"
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load private configuration: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
        return module
    finally:
        sys.modules.pop(module_name, None)


def serialized_value(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, time):
        return value.isoformat()
    return value


def render_private_config(values: dict[str, Any], overrides: dict[str, Any]) -> str:
    lines = [
        '"""Private OPPW account credentials and explicit canonical overrides.\n\n',
        "Generated by tools/migrate_mt5_config.py after exact-value validation.\n",
        '"""\n\n',
        "from __future__ import annotations\n\n",
    ]
    for field_name, constant_name in CREDENTIAL_FIELDS.items():
        lines.append(f"{constant_name} = {serialized_value(values[field_name])!r}\n")
    lines.append("\nOVERRIDES = {\n")
    for field_name in sorted(overrides):
        lines.append(f"    {field_name!r}: {serialized_value(overrides[field_name])!r},\n")
    lines.append("}\n")
    return "".join(lines)


def migrate_file(repo_root: Path, account: str, config_path: Path | None = None) -> bool:
    repo_root = repo_root.resolve()
    account = account.upper()
    if account not in ACCOUNTS:
        raise RuntimeError(f"Unsupported account: {account}")
    mt5_dir = repo_root / "mt5"
    if str(mt5_dir) not in sys.path:
        sys.path.insert(0, str(mt5_dir))

    from oppw_core.account_config import (  # pylint: disable=import-outside-toplevel
        build_account_config,
        default_config,
        load_private_overrides,
        validate_config,
    )
    from oppw_core.settings import Config  # pylint: disable=import-outside-toplevel

    path = config_path or mt5_dir / account.lower() / PRIVATE_FILENAMES[account]
    path = path.resolve()
    if not path.is_file():
        raise RuntimeError(f"Private configuration does not exist: {path}")

    with without_oppw_environment():
        module = load_module(path)
        if not hasattr(module, "Config"):
            current = build_account_config(
                account,
                path.parent,
                load_private_overrides(path),
                environ={},
            )
            validate_config(current)
            print(f"CONFIG ALREADY MIGRATED account={account} path={path}")
            return False
        legacy = module.Config()

    canonical_fields = tuple(field.name for field in fields(Config))
    missing = [name for name in canonical_fields if not hasattr(legacy, name)]
    if missing:
        raise RuntimeError(
            f"Legacy {account} Config is missing canonical fields: {', '.join(missing)}"
        )
    values = {name: getattr(legacy, name) for name in canonical_fields}
    defaults = default_config(account, path.parent)
    overrides = {
        name: values[name]
        for name in canonical_fields
        if name not in CREDENTIAL_FIELDS and values[name] != getattr(defaults, name)
    }
    rendered = render_private_config(values, overrides)
    temporary = path.with_name(f".{path.stem}.{uuid.uuid4().hex}.migration.py")
    try:
        temporary.write_text(rendered, encoding="utf-8", newline="\n")
        with without_oppw_environment():
            migrated = build_account_config(
                account,
                path.parent,
                load_private_overrides(temporary),
                environ={},
            )
        validate_config(migrated)
        mismatched = [
            name for name in canonical_fields if getattr(migrated, name) != values[name]
        ]
        if mismatched:
            raise RuntimeError(
                f"Migration validation changed {account} fields: {', '.join(mismatched)}"
            )
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()
    print(
        f"CONFIG MIGRATED account={account} path={path} "
        f"overrides={len(overrides)} values_verified={len(canonical_fields)}"
    )
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Migrate private OPPW Config copies to credential-and-override files."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
    )
    parser.add_argument("--account", choices=("demo", "real", "all"), default="all")
    args = parser.parse_args()
    accounts = ACCOUNTS if args.account == "all" else (args.account.upper(),)
    for account in accounts:
        migrate_file(args.repo_root, account)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
